# -*- coding: utf-8 -*-
"""PCG_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cAiV2vr-U6oj2S35u_L0S-ZrFmRPD5y

# PCG (Phonocardiogram) Advanced Analysis Pipeline

**Modules:**
1. Heart Sound Segmentation — peak-seeded boundary detection
2. Normal vs. Abnormal Classification — rule-based + Isolation Forest  
3. Murmur Detection & Grading — within Nyquist limit

> **Note on Sample Rate:** ESP32 records at 500 Hz (Nyquist = 250 Hz).  
> This captures S1 (20–150 Hz) and most S2 (50–200 Hz) adequately.  
> For murmur analysis above 250 Hz, increase to ≥2000 Hz.

## 1. Imports
"""

# Commented out IPython magic to ensure Python compatibility.
# ==================================================
# IMPORTS
# ==================================================

# %matplotlib inline

import warnings
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

from scipy.io import wavfile
from scipy.io.wavfile import write as wav_write
from scipy.signal import (
    butter,
    filtfilt,
    iirnotch,
    find_peaks,
    savgol_filter,
    hilbert,
    spectrogram,
)
from scipy.ndimage import uniform_filter1d

import pywt
import librosa

from IPython.display import display, Audio, FileLink

warnings.filterwarnings("ignore")

plt.rcParams.update({
    "figure.dpi": 120,
    "figure.facecolor": "white",
    "axes.grid": True,
    "grid.alpha": 0.3,
    "grid.linestyle": "--",
    "font.size": 11,
})

print("✓ Signal-processing imports successful")

# ==================================================
# CONFIGURATION — PCG Signal Analysis Pipeline
# ==================================================

FILENAME = Path("/content/aman1_.wav")

LOWCUT = 25.0
HIGHCUT = 200.0

NOTCH_FREQS = (50.0, 100.0, 150.0)
NOTCH_Q = 35.0

FILTER_ORDER = 4
WAVELET = "db6"
WAVELET_LEVEL = 4
WAVELET_THRESH_SCALE = 0.6

ENVELOPE_CUTOFF = 8.0
MIN_PEAK_DIST = 0.25

BPM_MIN = 40
BPM_MAX = 200

NORMAL_RANGES = {
    "s1_duration_ms": (50, 200),
    "s2_duration_ms": (40, 150),
    "systolic_ms": (150, 450),
    "diastolic_ms": (150, 1200),
    "s1_s2_amp_ratio": (0.5, 3.0),
    "heart_rate_bpm": (45, 180),
}

MURMUR_GRADE_THRESHOLDS = [0.15, 0.30, 0.50, 0.70, 0.90]
MURMUR_DETECTION_RATIO = 0.35

print("✓ Configuration loaded")
print(f"Input file: {FILENAME}")
print(f"File exists: {FILENAME.exists()}")
print(f"Bandpass range: {LOWCUT}-{HIGHCUT} Hz")
print(f"Notch frequencies: {NOTCH_FREQS}")
print(f"Wavelet: {WAVELET}, level={WAVELET_LEVEL}, threshold scale={WAVELET_THRESH_SCALE}")
print(f"Envelope cutoff: {ENVELOPE_CUTOFF} Hz")
print(f"Minimum peak distance: {MIN_PEAK_DIST} s")
print(f"Murmur-like detection ratio: {MURMUR_DETECTION_RATIO}")

"""## 2. Signal Processing Filters"""

# ==================================================
# CONFIGURATION — PCG Signal Analysis Pipeline
# ==================================================

from pathlib import Path

# --------------------------------------------------
# Input WAV file
# --------------------------------------------------
FILENAME = Path("/content/aman1_.wav")


# --------------------------------------------------
# Bandpass filtering settings
# --------------------------------------------------
LOWCUT = 25.0
HIGHCUT = 200.0


# --------------------------------------------------
# Powerline noise removal
# --------------------------------------------------
NOTCH_FREQS = (50.0, 100.0, 150.0)
NOTCH_Q = 35.0


# --------------------------------------------------
# Filtering / denoising settings
# --------------------------------------------------
FILTER_ORDER = 4
WAVELET = "db6"
WAVELET_LEVEL = 4
WAVELET_THRESH_SCALE = 0.6


# --------------------------------------------------
# Envelope / peak detection settings
# --------------------------------------------------
ENVELOPE_CUTOFF = 8.0
MIN_PEAK_DIST = 0.25


# --------------------------------------------------
# Physiological heart-rate limits
# --------------------------------------------------
BPM_MIN = 40
BPM_MAX = 200


# --------------------------------------------------
# Physiological normal ranges for rule-based screening
# --------------------------------------------------
NORMAL_RANGES = {
    "s1_duration_ms": (50, 200),
    "s2_duration_ms": (40, 150),
    "systolic_ms": (150, 450),
    "diastolic_ms": (150, 1200),
    "s1_s2_amp_ratio": (0.5, 3.0),
    "heart_rate_bpm": (45, 180),
}


# --------------------------------------------------
# Murmur-like activity thresholds
# --------------------------------------------------
MURMUR_GRADE_THRESHOLDS = [0.15, 0.30, 0.50, 0.70, 0.90]
MURMUR_DETECTION_RATIO = 0.35


# --------------------------------------------------
# Configuration check
# --------------------------------------------------
print("✓ Configuration loaded")
print(f"Input file: {FILENAME}")
print(f"File exists: {FILENAME.exists()}")
print(f"Bandpass range: {LOWCUT}-{HIGHCUT} Hz")
print(f"Notch frequencies: {NOTCH_FREQS}")
print(f"Wavelet: {WAVELET}, level={WAVELET_LEVEL}, threshold scale={WAVELET_THRESH_SCALE}")
print(f"Envelope cutoff: {ENVELOPE_CUTOFF} Hz")
print(f"Minimum peak distance: {MIN_PEAK_DIST} s")
print(f"Murmur-like detection ratio: {MURMUR_DETECTION_RATIO}")

"""## 3. Load & Preprocess Signal"""

# ==================================================
# LOAD & PREPROCESS SIGNAL
# ==================================================

if not FILENAME.exists():
    raise FileNotFoundError(
        f"Input WAV file not found: {FILENAME}\n"
        "Please upload the file to Colab or update FILENAME."
    )

sample_rate, raw_data = wavfile.read(str(FILENAME))
raw_data_original = raw_data.copy()

raw_dtype = raw_data_original.dtype
raw_shape = raw_data_original.shape

if raw_data.ndim > 1:
    raw_data = np.mean(raw_data, axis=1)

if np.issubdtype(raw_data.dtype, np.integer):
    max_val = np.iinfo(raw_data.dtype).max
    data = raw_data.astype(np.float64) / max_val
else:
    data = raw_data.astype(np.float64)

data = data - np.mean(data)

n_samples = len(data)
duration = n_samples / sample_rate
nyq = sample_rate / 2.0
time_axis = np.linspace(0, duration, n_samples, endpoint=False)

print(f"File:          {FILENAME}")
print(f"Exists:        {FILENAME.exists()}")
print(f"Raw dtype:     {raw_dtype}")
print(f"Raw shape:     {raw_shape}")
print(f"Sample rate:   {sample_rate} Hz")
print(f"Nyquist:       {nyq:.1f} Hz")
print(f"Duration:      {duration:.2f} s")
print(f"Samples:       {n_samples:,}")
print(f"Data dtype:    {data.dtype}")
print(f"Data range:    [{data.min():.4f}, {data.max():.4f}]")
print(f"Data mean:     {np.mean(data):.6f}")
print(f"Data std:      {np.std(data):.6f}")

if HIGHCUT >= nyq:
    print(f"⚠ HIGHCUT ({HIGHCUT} Hz) >= Nyquist ({nyq:.1f} Hz). It will be clamped later.")

# ==================================================
# RAW ORIGINAL RECORDING PREVIEW
# ==================================================

raw_time_axis = np.linspace(
    0,
    len(raw_data_original) / sample_rate,
    len(raw_data_original),
    endpoint=False
)

print(f"Raw original dtype: {raw_data_original.dtype}")
print(f"Raw original shape: {raw_data_original.shape}")
print(f"Raw original range: [{raw_data_original.min()}, {raw_data_original.max()}]")
print(f"Raw file path: {FILENAME}")

plt.figure(figsize=(14, 4))

if raw_data_original.ndim == 1:
    plt.plot(raw_time_axis, raw_data_original, linewidth=0.7)
    plt.ylabel("Raw amplitude")
else:
    for ch in range(raw_data_original.shape[1]):
        plt.plot(raw_time_axis, raw_data_original[:, ch], linewidth=0.7, alpha=0.8, label=f"Channel {ch + 1}")
    plt.legend()
    plt.ylabel("Raw amplitude")

plt.title("Raw Original WAV Signal")
plt.xlabel("Time [s]")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

display(Audio(filename=str(FILENAME)))

# ==================================================
# SAVE NORMALIZED + DC-REMOVED SIGNAL
# ==================================================

data_norm_dc_removed = data / (np.max(np.abs(data)) + 1e-10)

normalized_dc_path = "/content/normalized_dc_removed.wav"

wav_write(
    normalized_dc_path,
    sample_rate,
    (data_norm_dc_removed * 32767).astype(np.int16)
)

print("✓ Normalized + DC-removed WAV saved")
print(f"Saved file:      {normalized_dc_path}")
print(f"Sample rate:     {sample_rate} Hz")
print(f"Duration:        {duration:.2f} s")
print(f"Samples:         {n_samples:,}")
print(f"Processed range: [{data_norm_dc_removed.min():.4f}, {data_norm_dc_removed.max():.4f}]")

plt.figure(figsize=(14, 4))
plt.plot(time_axis, data_norm_dc_removed, linewidth=0.7)
plt.title("Normalized and DC-Removed PCG Signal")
plt.xlabel("Time [s]")
plt.ylabel("Normalized amplitude")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

display(Audio(filename=normalized_dc_path))
display(FileLink(normalized_dc_path))

from google.colab import files

files.download(normalized_dc_path)

# ==================================================
# APPLY FILTER PIPELINE AND SAVE FILTERED WAV
# ==================================================

def signal_stats(name, x):
    print(
        f"{name:<18} | "
        f"min={np.min(x): .5f}, "
        f"max={np.max(x): .5f}, "
        f"mean={np.mean(x): .5f}, "
        f"std={np.std(x): .5f}, "
        f"rms={np.sqrt(np.mean(x**2)): .5f}"
    )


# Stage 1: Notch filtering
data_notched = multi_notch_filter(
    data,
    sample_rate,
    freqs=NOTCH_FREQS,
    q=NOTCH_Q
)

# Stage 2: Bandpass filtering
data_bp = bandpass_filter(
    data_notched,
    LOWCUT,
    HIGHCUT,
    sample_rate,
    FILTER_ORDER
)

# Stage 3: Wavelet denoising
data_denoised = wavelet_denoise(
    data_bp,
    WAVELET,
    WAVELET_LEVEL,
    thresh_scale=WAVELET_THRESH_SCALE
)[:n_samples]

# Stage 4: Savitzky-Golay smoothing
if len(data_denoised) >= 11:
    filtered = savgol_filter(
        data_denoised,
        window_length=11,
        polyorder=3
    )
else:
    filtered = data_denoised.copy()

# Normalize filtered signal for plotting/audio/export
filtered_norm = filtered / (np.max(np.abs(filtered)) + 1e-10)

# Save filtered WAV
filtered_path = "/content/filtered_pcg.wav"

wav_write(
    filtered_path,
    sample_rate,
    (filtered_norm * 32767).astype(np.int16)
)

effective_highcut = min(HIGHCUT, nyq - 1.0)

print("✓ Filter pipeline complete")
print(f"Effective bandpass range: {LOWCUT}-{effective_highcut:.1f} Hz")
print(f"Saved filtered WAV: {filtered_path}")
print()

signal_stats("Input data", data)
signal_stats("After notch", data_notched)
signal_stats("After bandpass", data_bp)
signal_stats("After wavelet", data_denoised)
signal_stats("Final filtered", filtered)
signal_stats("Filtered norm", filtered_norm)

# Plot comparison
plt.figure(figsize=(14, 6))

plt.subplot(2, 1, 1)
plt.plot(time_axis, data, linewidth=0.7)
plt.title("Input Signal After Normalization and DC Removal")
plt.xlabel("Time [s]")
plt.ylabel("Amplitude")
plt.grid(True, alpha=0.3)

plt.subplot(2, 1, 2)
plt.plot(time_axis, filtered_norm, linewidth=0.7)
plt.title("Filtered PCG Signal")
plt.xlabel("Time [s]")
plt.ylabel("Normalized amplitude")
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("Filtered signal preview:")
display(Audio(filename=filtered_path))

from google.colab import files

files.download(filtered_path)

# ==================================================
# COMPARE RAW VS FILTERED
# ==================================================

raw_plot = raw_data.astype(np.float64)
raw_plot = raw_plot - np.mean(raw_plot)
raw_plot = raw_plot / (np.max(np.abs(raw_plot)) + 1e-10)

filtered_plot = filtered / (np.max(np.abs(filtered)) + 1e-10)

fig, axes = plt.subplots(2, 1, figsize=(15, 6), sharex=True)

axes[0].plot(time_axis, raw_plot, color="gray", lw=0.4)
axes[0].set_title("Raw PCG Signal", fontweight="bold")
axes[0].set_ylabel("Normalized amplitude")
axes[0].grid(True, alpha=0.3)

axes[1].plot(time_axis, filtered_plot, color="steelblue", lw=0.6)
axes[1].set_title(
    f"After Notch + Bandpass ({LOWCUT}-{min(HIGHCUT, nyq - 1):.0f} Hz) + Wavelet + SG",
    fontweight="bold"
)
axes[1].set_ylabel("Normalized amplitude")
axes[1].set_xlabel("Time (seconds)")
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# # ==================================================
# # OPTIONAL ROBUST SIGNAL FOR ENVELOPE DETECTION
# # ==================================================

# clip_percentile = 99.5
# clip_limit = np.percentile(np.abs(filtered), clip_percentile)
# clip_limit = max(clip_limit, 1e-6)

# filtered_for_envelope = np.clip(filtered, -clip_limit, clip_limit)
# filtered_for_envelope_norm = filtered_for_envelope / (np.max(np.abs(filtered_for_envelope)) + 1e-10)

# print(f"Clip percentile: {clip_percentile}")
# print(f"Clip limit:      {clip_limit:.6f}")

# plt.figure(figsize=(14, 4))
# plt.plot(time_axis, filtered_norm, linewidth=0.6, alpha=0.5, label="Filtered normalized")
# plt.plot(time_axis, filtered_for_envelope_norm, linewidth=0.8, alpha=0.8, label="Percentile-clipped for envelope")
# plt.title("Filtered Signal vs Percentile-Clipped Signal")
# plt.xlabel("Time [s]")
# plt.ylabel("Normalized amplitude")
# plt.legend()
# plt.grid(True, alpha=0.3)
# plt.tight_layout()
# plt.show()

"""## 4. Envelope & S1/S2 Peak Detection"""

# ==================================================
# ENVELOPE FUNCTIONS
# ==================================================

def lowpass_filter(data, cutoff, fs, order=2):
    nyq = 0.5 * fs
    effective_cutoff = min(cutoff, nyq - 1.0)

    if effective_cutoff <= 0:
        raise ValueError(f"Invalid lowpass cutoff: {cutoff}")

    b, a = butter(order, effective_cutoff / nyq, btype="low")
    return filtfilt(b, a, data)


def shannon_envelope(signal, sr, cutoff=8.0):
    x = np.asarray(signal, dtype=np.float64)
    x = x / (np.max(np.abs(x)) + 1e-10)

    eps = 1e-10
    shannon_energy = -(x ** 2) * np.log((x ** 2) + eps)

    envelope = lowpass_filter(
        shannon_energy,
        cutoff=cutoff,
        fs=sr,
        order=2
    )

    envelope = np.maximum(envelope, 0)
    envelope = envelope / (np.max(envelope) + 1e-10)

    return envelope


print("✓ Envelope functions ready")

# ==================================================
# ENVELOPE & S1/S2 PEAK DETECTION — PHYSIOLOGICAL PAIRING VERSION
# ==================================================

# Shannon energy envelope
envelope = shannon_envelope(
    filtered,
    sample_rate,
    ENVELOPE_CUTOFF
)

# Adaptive peak detection
threshold = np.percentile(envelope, 75)

peaks, properties = find_peaks(
    envelope,
    height=threshold,
    distance=int(sample_rate * MIN_PEAK_DIST),
    prominence=threshold * 0.3
)

# --------------------------------------------------
# Physiological timing constraints
# --------------------------------------------------
# S1→S2 is usually shorter than S2→next S1.
# These limits are intentionally flexible to handle noisy PCG recordings.

S1S2_MIN = 0.07
S1S2_MAX = 0.50
S2S1_MIN = 0.18
S2S1_MAX = 1.40

# --------------------------------------------------
# Physiological S1/S2 pairing
# --------------------------------------------------

s1_peaks = []
s2_peaks = []
used_peaks = set()
cycle_pairs = []

i = 0

while i < len(peaks) - 1:
    p1 = int(peaks[i])
    p2 = int(peaks[i + 1])

    dt12 = (p2 - p1) / sample_rate

    if S1S2_MIN <= dt12 <= S1S2_MAX:
        next_gap_valid = True

        if i + 2 < len(peaks):
            p3 = int(peaks[i + 2])
            dt23 = (p3 - p2) / sample_rate
            next_gap_valid = S2S1_MIN <= dt23 <= S2S1_MAX

        if next_gap_valid:
            s1_peaks.append(p1)
            s2_peaks.append(p2)

            used_peaks.add(p1)
            used_peaks.add(p2)

            cycle_pairs.append({
                "s1_peak": p1,
                "s2_peak": p2,
                "s1_time": p1 / sample_rate,
                "s2_time": p2 / sample_rate,
                "s1_s2_interval_s": dt12,
            })

            i += 2
        else:
            i += 1
    else:
        i += 1

s1_peaks = np.array(sorted(set(s1_peaks)), dtype=int)
s2_peaks = np.array(sorted(set(s2_peaks)), dtype=int)

used_peaks = set(s1_peaks.tolist()) | set(s2_peaks.tolist())

unassigned_peaks = np.array(
    [int(p) for p in peaks if int(p) not in used_peaks],
    dtype=int
)

overlap_peaks = np.intersect1d(s1_peaks, s2_peaks)

# --------------------------------------------------
# Summary
# --------------------------------------------------

print("Physiological S1/S2 Pairing")
print("=" * 70)
print(f"Peaks detected:       {len(peaks)}")
print(f"S1 peaks:             {len(s1_peaks)}")
print(f"S2 peaks:             {len(s2_peaks)}")
print(f"Unassigned peaks:     {len(unassigned_peaks)}")
print(f"Overlap peaks:        {len(overlap_peaks)}")
print(f"Accepted S1/S2 pairs: {len(cycle_pairs)}")
print(f"Threshold:            {threshold:.4f}")
print()
print("Timing constraints")
print("-" * 70)
print(f"S1→S2 valid range:    {S1S2_MIN:.2f}–{S1S2_MAX:.2f} s")
print(f"S2→S1 valid range:    {S2S1_MIN:.2f}–{S2S1_MAX:.2f} s")

if len(peaks) > 1:
    peak_intervals = np.diff(peaks) / sample_rate
    print()
    print("Detected peak intervals")
    print("-" * 70)
    print(f"Mean peak interval:   {np.mean(peak_intervals):.3f} s")
    print(f"Median peak interval: {np.median(peak_intervals):.3f} s")

if len(s1_peaks) > 1:
    rr_intervals = np.diff(s1_peaks) / sample_rate
    valid_rr = rr_intervals[(rr_intervals > 0.3) & (rr_intervals < 1.5)]

    if len(valid_rr) > 0:
        hr_estimate = 60.0 / np.median(valid_rr)
        print()
        print("Heart-rate estimate")
        print("-" * 70)
        print(f"Valid S1-S1 intervals: {len(valid_rr)} / {len(rr_intervals)}")
        print(f"Estimated HR from S1:  {hr_estimate:.1f} bpm")
    else:
        print()
        print("Estimated HR from S1: unavailable")
else:
    print()
    print("Estimated HR from S1: unavailable")

# ==================================================
# VISUALIZE ENVELOPE AND S1/S2 PEAKS
# ==================================================

plt.figure(figsize=(15, 6))

plt.plot(
    time_axis,
    filtered_norm,
    color="steelblue",
    linewidth=0.6,
    alpha=0.5,
    label="Filtered signal"
)

plt.plot(
    time_axis,
    envelope,
    color="black",
    linewidth=1.2,
    label="Shannon envelope"
)

plt.axhline(
    threshold,
    color="red",
    linestyle="--",
    linewidth=1.0,
    label=f"Threshold = {threshold:.3f}"
)

plt.scatter(
    s1_peaks / sample_rate,
    envelope[s1_peaks],
    color="green",
    s=45,
    marker="o",
    label="S1 peaks",
    zorder=4
)

plt.scatter(
    s2_peaks / sample_rate,
    envelope[s2_peaks],
    color="purple",
    s=45,
    marker="x",
    label="S2 peaks",
    zorder=4
)

if len(unassigned_peaks):
    plt.scatter(
        unassigned_peaks / sample_rate,
        envelope[unassigned_peaks],
        color="gray",
        s=40,
        marker="D",
        label="Unassigned peaks",
        zorder=4
    )

plt.title("Shannon Envelope with Physiological S1/S2 Pairing")
plt.xlabel("Time [s]")
plt.ylabel("Normalized amplitude / envelope")
plt.legend(loc="upper right")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# ==================================================
# ZOOMED ENVELOPE AND S1/S2 PEAKS
# ==================================================

t_start = 5
t_end = 12

mask = (time_axis >= t_start) & (time_axis <= t_end)

peaks_zoom = peaks[
    (peaks / sample_rate >= t_start) &
    (peaks / sample_rate <= t_end)
]

s1_zoom = s1_peaks[
    (s1_peaks / sample_rate >= t_start) &
    (s1_peaks / sample_rate <= t_end)
]

s2_zoom = s2_peaks[
    (s2_peaks / sample_rate >= t_start) &
    (s2_peaks / sample_rate <= t_end)
]

unassigned_zoom = unassigned_peaks[
    (unassigned_peaks / sample_rate >= t_start) &
    (unassigned_peaks / sample_rate <= t_end)
]

plt.figure(figsize=(15, 5))

plt.plot(
    time_axis[mask],
    filtered_norm[mask],
    color="steelblue",
    linewidth=0.7,
    alpha=0.6,
    label="Filtered signal"
)

plt.plot(
    time_axis[mask],
    envelope[mask],
    color="black",
    linewidth=1.3,
    label="Shannon envelope"
)

plt.axhline(
    threshold,
    color="red",
    linestyle="--",
    linewidth=1.0,
    label=f"Threshold = {threshold:.3f}"
)

plt.scatter(
    peaks_zoom / sample_rate,
    envelope[peaks_zoom],
    color="orange",
    s=35,
    label="Detected peaks",
    zorder=3
)

if len(s1_zoom):
    plt.scatter(
        s1_zoom / sample_rate,
        envelope[s1_zoom],
        color="green",
        s=65,
        marker="o",
        label="S1 peaks",
        zorder=4
    )

if len(s2_zoom):
    plt.scatter(
        s2_zoom / sample_rate,
        envelope[s2_zoom],
        color="purple",
        s=65,
        marker="x",
        label="S2 peaks",
        zorder=4
    )

if len(unassigned_zoom):
    plt.scatter(
        unassigned_zoom / sample_rate,
        envelope[unassigned_zoom],
        color="gray",
        s=55,
        marker="D",
        label="Unassigned peaks",
        zorder=4
    )

plt.title(f"Zoomed S1/S2 Peak Detection ({t_start}-{t_end} s)")
plt.xlabel("Time [s]")
plt.ylabel("Normalized amplitude / envelope")
plt.legend(loc="upper right")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# ==================================================
# CLEAN ENVELOPE PLOT WITH S1/S2 MARKERS
# ==================================================

fig, ax = plt.subplots(figsize=(15, 4))

ax.plot(
    time_axis,
    envelope,
    color="black",
    lw=1.2,
    label="Shannon envelope"
)

ax.axhline(
    y=threshold,
    color="red",
    ls="--",
    alpha=0.7,
    label=f"Threshold = {threshold:.3f}"
)

if len(s1_peaks):
    ax.plot(
        s1_peaks / sample_rate,
        envelope[s1_peaks],
        "o",
        color="green",
        ms=7,
        label=f"S1 (n={len(s1_peaks)})",
        zorder=5
    )

if len(s2_peaks):
    ax.plot(
        s2_peaks / sample_rate,
        envelope[s2_peaks],
        "x",
        color="purple",
        ms=8,
        label=f"S2 (n={len(s2_peaks)})",
        zorder=5
    )

if "unassigned_peaks" in globals() and len(unassigned_peaks):
    ax.plot(
        unassigned_peaks / sample_rate,
        envelope[unassigned_peaks],
        "D",
        color="gray",
        ms=5,
        label=f"Unassigned (n={len(unassigned_peaks)})",
        zorder=4
    )

ax.set_title(
    "Shannon Energy Envelope with Physiological S1/S2 Pairing",
    fontweight="bold")
ax.set_xlabel("Time (seconds)")
ax.set_ylabel("Normalized envelope")
ax.legend(loc="upper right")
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""---
## Heart Sound Segmentation

Segments the signal into four cardiac phases per cycle:  
**S1 → Systole → S2 → Diastole → S1 → ...**

Uses envelope width at 40% of peak height to estimate S1/S2 boundaries,  
then fills systole and diastole in the gaps.
"""

# ==================================================
# SEGMENTATION FUNCTIONS — FOUR STATES ONLY
# ==================================================

def estimate_sound_width(envelope, peak_idx, sr, max_width_s=0.15, relative_height=0.4):
    peak_idx = int(peak_idx)
    half_height = envelope[peak_idx] * relative_height
    max_w = int(sr * max_width_s)

    left = peak_idx
    for j in range(peak_idx, max(0, peak_idx - max_w), -1):
        if envelope[j] < half_height:
            left = j
            break

    right = peak_idx
    for j in range(peak_idx, min(len(envelope), peak_idx + max_w)):
        if envelope[j] < half_height:
            right = j
            break

    return left, right


def build_sound_bounds(envelope, peaks, sr, max_width_s, relative_height=0.4):
    bounds = []

    for pk in peaks:
        left, right = estimate_sound_width(
            envelope,
            pk,
            sr,
            max_width_s=max_width_s,
            relative_height=relative_height
        )

        if right > left:
            bounds.append((int(pk), int(left), int(right)))

    return sorted(bounds, key=lambda x: x[0])


def segment_heart_sounds(filtered, envelope, s1_peaks, s2_peaks, sr, cycle_pairs=None):
    n = len(filtered)

    # 0=S1, 1=Systole, 2=S2, 3=Diastole
    states = np.full(n, 3, dtype=int)

    s1_bounds = build_sound_bounds(
        envelope,
        s1_peaks,
        sr,
        max_width_s=0.08,
        relative_height=0.4
    )

    s2_bounds = build_sound_bounds(
        envelope,
        s2_peaks,
        sr,
        max_width_s=0.07,
        relative_height=0.4
    )

    s1_bound_map = {pk: (left, right) for pk, left, right in s1_bounds}
    s2_bound_map = {pk: (left, right) for pk, left, right in s2_bounds}

    # Mark S1 and S2 sounds
    for _, left, right in s1_bounds:
        states[left:right] = 0

    for _, left, right in s2_bounds:
        states[left:right] = 2

    if cycle_pairs is not None and len(cycle_pairs) > 0:
        pair_list = []

        for pair in cycle_pairs:
            if isinstance(pair, dict):
                s1_pk = int(pair["s1_peak"])
                s2_pk = int(pair["s2_peak"])
            else:
                s1_pk = int(pair[0])
                s2_pk = int(pair[1])

            if s1_pk in s1_bound_map and s2_pk in s2_bound_map:
                pair_list.append((s1_pk, s2_pk))

        pair_list = sorted(pair_list, key=lambda x: x[0])

        for i, (s1_pk, s2_pk) in enumerate(pair_list):
            s1_left, s1_right = s1_bound_map[s1_pk]
            s2_left, s2_right = s2_bound_map[s2_pk]

            systole_gap_s = (s2_left - s1_right) / sr

            if 0.03 <= systole_gap_s <= 0.55:
                states[s1_right:s2_left] = 1

            if i + 1 < len(pair_list):
                next_s1_pk, _ = pair_list[i + 1]

                if next_s1_pk in s1_bound_map:
                    next_s1_left, _ = s1_bound_map[next_s1_pk]

                    diastole_gap_s = (next_s1_left - s2_right) / sr

                    if 0.08 <= diastole_gap_s <= 1.30:
                        states[s2_right:next_s1_left] = 3

    else:
        s1_simple_bounds = [(left, right) for _, left, right in s1_bounds]
        s2_simple_bounds = [(left, right) for _, left, right in s2_bounds]

        for _, s1_end in s1_simple_bounds:
            next_s2 = [s2_l for s2_l, _ in s2_simple_bounds if s2_l > s1_end]

            if next_s2:
                gap_s = (next_s2[0] - s1_end) / sr

                if 0.05 <= gap_s <= 0.50:
                    states[s1_end:next_s2[0]] = 1

        for _, s2_end in s2_simple_bounds:
            next_s1 = [s1_l for s1_l, _ in s1_simple_bounds if s1_l > s2_end]

            if next_s1:
                gap_s = (next_s1[0] - s2_end) / sr

                if 0.10 <= gap_s <= 1.30:
                    states[s2_end:next_s1[0]] = 3

    state_names = ["S1", "Systole", "S2", "Diastole"]

    segments = []
    i = 0

    while i < n:
        j = i

        while j < n and states[j] == states[i]:
            j += 1

        segments.append((state_names[int(states[i])], i, j))
        i = j

    return states, segments


print("✓ Segmentation functions defined")

# ==================================================
# RUN SEGMENTATION AND REPORT RESULTS
# ==================================================

states, segments = segment_heart_sounds(
    filtered,
    envelope,
    s1_peaks,
    s2_peaks,
    sample_rate
)

STATE_NAMES = ["S1", "Systole", "S2", "Diastole"]

print("Segmentation Results")
print("=" * 70)
print(f"Total segments: {len(segments)}")
print(f"Signal duration: {duration:.2f} s")
print()

for sn in STATE_NAMES:
    durs = [
        (e - s) / sample_rate * 1000
        for name, s, e in segments
        if name == sn
    ]

    if durs:
        print(
            f"{sn:<10}: "
            f"{len(durs):3d} segments | "
            f"mean={np.mean(durs):7.1f} ms | "
            f"std={np.std(durs):6.1f} ms | "
            f"min={np.min(durs):6.1f} ms | "
            f"max={np.max(durs):6.1f} ms"
        )
    else:
        print(f"{sn:<10}: no segments detected")

print()
print("State sample coverage")
print("=" * 70)

for idx, sn in enumerate(STATE_NAMES):
    count_samples = np.sum(states == idx)
    pct = 100 * count_samples / len(states)

    print(
        f"{sn:<10}: "
        f"{count_samples:6d} samples | "
        f"{pct:5.1f}% of signal"
    )

# ==================================================
# FULL RECORDING SEGMENTATION VIEW
# ==================================================

STATE_COLORS = {
    "S1": "#e74c3c",
    "Systole": "#f39c12",
    "S2": "#3498db",
    "Diastole": "#2ecc71",
}

fig, ax = plt.subplots(figsize=(16, 4))

ax.plot(
    time_axis,
    filtered_norm,
    color="black",
    lw=0.5,
    alpha=0.7,
    label="Filtered signal"
)

for state_name, start_idx, end_idx in segments:
    ax.axvspan(
        start_idx / sample_rate,
        end_idx / sample_rate,
        alpha=0.28,
        color=STATE_COLORS.get(state_name, "#bdc3c7")
    )

patches = [
    mpatches.Patch(
        color=color,
        alpha=0.5,
        label=state_name
    )
    for state_name, color in STATE_COLORS.items()
]

ax.legend(
    handles=patches,
    loc="upper right",
    fontsize=9,
    ncol=5
)

ax.set_title(
    "Heart Sound Segmentation: S1 → Systole → S2 → Diastole + Unknown",
    fontweight="bold"
)

ax.set_xlabel("Time (seconds)")
ax.set_ylabel("Normalized amplitude")
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# ==================================================
# ZOOMED SEGMENTATION DETAIL VIEW
# ==================================================

ZOOM_START = 5.0
ZOOM_END = 20.0

mask = (time_axis >= ZOOM_START) & (time_axis < ZOOM_END)

STATE_COLORS = {
    "S1": "#e74c3c",
    "Systole": "#f39c12",
    "S2": "#3498db",
    "Diastole": "#2ecc71",
}

zoom_patches = [
    mpatches.Patch(
        color=color,
        alpha=0.5,
        label=state_name
    )
    for state_name, color in STATE_COLORS.items()
]

fig, axes = plt.subplots(3, 1, figsize=(15, 11), sharex=False)

# --------------------------------------------------
# Signal + envelope
# --------------------------------------------------
axes[0].plot(
    time_axis[mask],
    filtered_norm[mask],
    color="#2c3e50",
    lw=0.8,
    label="Filtered signal"
)

ax0t = axes[0].twinx()

ax0t.plot(
    time_axis[mask],
    envelope[mask],
    color="#ff7f0e",
    lw=1.5,
    alpha=0.85,
    label="Shannon envelope"
)

zs1 = s1_peaks[
    (s1_peaks / sample_rate >= ZOOM_START) &
    (s1_peaks / sample_rate < ZOOM_END)
]

zs2 = s2_peaks[
    (s2_peaks / sample_rate >= ZOOM_START) &
    (s2_peaks / sample_rate < ZOOM_END)
]

if len(zs1):
    ax0t.plot(
        zs1 / sample_rate,
        envelope[zs1],
        "o",
        color="green",
        ms=8,
        label="S1"
    )

if len(zs2):
    ax0t.plot(
        zs2 / sample_rate,
        envelope[zs2],
        "x",
        color="purple",
        ms=8,
        label="S2"
    )

axes[0].set_title(
    f"Signal + Envelope ({ZOOM_START:.1f}–{ZOOM_END:.1f} s)",
    fontweight="bold"
)

axes[0].set_ylabel("Filtered amplitude")
ax0t.set_ylabel("Envelope")
axes[0].grid(True, alpha=0.3)
ax0t.legend(loc="upper right")

# --------------------------------------------------
# Segmentation
# --------------------------------------------------
axes[1].plot(
    time_axis[mask],
    filtered_norm[mask],
    color="#2c3e50",
    lw=0.8
)

for state_name, start_idx, end_idx in segments:
    seg_start = start_idx / sample_rate
    seg_end = end_idx / sample_rate

    if seg_end >= ZOOM_START and seg_start <= ZOOM_END:
        axes[1].axvspan(
            max(seg_start, ZOOM_START),
            min(seg_end, ZOOM_END),
            alpha=0.35,
            color=STATE_COLORS.get(state_name, "#95a5a6")
        )

axes[1].legend(
    handles=zoom_patches,
    loc="upper right",
    fontsize=9,
    ncol=4
)

axes[1].set_title("Segmentation Detail", fontweight="bold")
axes[1].set_ylabel("Filtered amplitude")
axes[1].set_xlim(ZOOM_START, ZOOM_END)
axes[1].grid(True, alpha=0.3)

# --------------------------------------------------
# Spectrogram
# --------------------------------------------------
zsig = filtered[mask]

nperseg = min(64, max(16, len(zsig) // 4))
noverlap = int(nperseg * 0.75)

if len(zsig) > nperseg:
    f_, t_, S_ = spectrogram(
        zsig,
        fs=sample_rate,
        nperseg=nperseg,
        noverlap=noverlap
    )

    pcm = axes[2].pcolormesh(
        t_ + ZOOM_START,
        f_,
        10 * np.log10(S_ + 1e-10),
        shading="gouraud",
        cmap="inferno"
    )

    fig.colorbar(
        pcm,
        ax=axes[2],
        label="Power (dB)"
    )
else:
    axes[2].text(
        0.5,
        0.5,
        "Signal window too short for spectrogram",
        ha="center",
        va="center",
        transform=axes[2].transAxes
    )

axes[2].set_title("Spectrogram", fontweight="bold")
axes[2].set_xlabel("Time (seconds)")
axes[2].set_ylabel("Frequency (Hz)")
axes[2].set_ylim(0, nyq)
axes[2].set_xlim(ZOOM_START, ZOOM_END)
axes[2].grid(False)

plt.tight_layout()
plt.show()

"""---
## Module 2: Normal vs. Abnormal Classification

Two approaches:
1. **Rule-based screening** — checks each cycle against physiological normal ranges
2. **Anomaly detection** — Isolation Forest on per-cycle feature vectors (flags statistical outliers)
"""

# ==================================================
# FEATURE EXTRACTION FUNCTIONS
# ==================================================

def spectral_centroid(x, sr):
    x = np.asarray(x, dtype=np.float64)

    if len(x) < 8:
        return 0.0

    mag = np.abs(np.fft.rfft(x))
    freqs = np.fft.rfftfreq(len(x), 1.0 / sr)

    return float(np.sum(freqs * mag) / (np.sum(mag) + 1e-10))


def zero_crossing_rate(x):
    x = np.asarray(x, dtype=np.float64)

    if len(x) < 2:
        return 0.0

    return float(np.sum(np.diff(np.sign(x)) != 0) / len(x))


def excess_kurtosis(x):
    x = np.asarray(x, dtype=np.float64)

    if len(x) < 4:
        return 0.0

    m = np.mean(x)
    s = np.std(x)

    if s < 1e-10:
        return 0.0

    return float(np.mean(((x - m) / s) ** 4) - 3)


def rms(x):
    x = np.asarray(x, dtype=np.float64)

    if len(x) == 0:
        return 0.0

    return float(np.sqrt(np.mean(x ** 2)))


def safe_mfcc_means(x, sr, n_mfcc=8):
    x = np.asarray(x, dtype=np.float64)

    if len(x) < 16:
        return np.zeros(n_mfcc, dtype=np.float64)

    n_fft = min(64, len(x))

    if n_fft < 16:
        return np.zeros(n_mfcc, dtype=np.float64)

    try:
        mfccs = librosa.feature.mfcc(
            y=x,
            sr=sr,
            n_mfcc=n_mfcc,
            n_fft=n_fft,
            hop_length=max(1, n_fft // 4)
        )

        return np.mean(mfccs, axis=1).astype(np.float64)

    except Exception:
        return np.zeros(n_mfcc, dtype=np.float64)


def is_valid_cycle_duration(
    s1_dur,
    s2_dur,
    systolic,
    diastolic,
    cycle_dur
):
    if not (45 <= s1_dur <= 200):
        return False

    if not (40 <= s2_dur <= 160):
        return False

    if not (150 <= systolic <= 500):
        return False

    if not (150 <= diastolic <= 1300):
        return False

    if not (400 <= cycle_dur <= 1500):
        return False

    return True


def extract_cycle_features(filtered, segments, sr):
    cycles = []
    rejected_cycles = []
    i = 0

    while i + 3 < len(segments):
        if (
            segments[i][0] == "S1" and
            segments[i + 1][0] == "Systole" and
            segments[i + 2][0] == "S2" and
            segments[i + 3][0] == "Diastole"
        ):
            s1_start, s1_end = segments[i][1], segments[i][2]
            sys_start, sys_end = segments[i + 1][1], segments[i + 1][2]
            s2_start, s2_end = segments[i + 2][1], segments[i + 2][2]
            dia_start, dia_end = segments[i + 3][1], segments[i + 3][2]

            s1_sig = filtered[s1_start:s1_end]
            sys_sig = filtered[sys_start:sys_end]
            s2_sig = filtered[s2_start:s2_end]
            dia_sig = filtered[dia_start:dia_end]
            full = filtered[s1_start:dia_end]

            if len(s1_sig) < 3 or len(s2_sig) < 3 or len(full) < 10:
                rejected_cycles.append({
                    "index": len(cycles) + len(rejected_cycles),
                    "reason": "too_short"
                })
                i += 1
                continue

            s1_rms = rms(s1_sig)
            s2_rms = rms(s2_sig)
            sys_rms = rms(sys_sig)
            dia_rms = rms(dia_sig)

            s1_dur = len(s1_sig) / sr * 1000
            s2_dur = len(s2_sig) / sr * 1000
            systolic = (s2_start - s1_start) / sr * 1000
            diastolic = (dia_end - s2_start) / sr * 1000
            cycle_dur = (dia_end - s1_start) / sr * 1000
            hr = 60000.0 / cycle_dur if cycle_dur > 0 else 0.0

            if not is_valid_cycle_duration(
                s1_dur,
                s2_dur,
                systolic,
                diastolic,
                cycle_dur
            ):
                rejected_cycles.append({
                    "index": len(cycles) + len(rejected_cycles),
                    "reason": "duration_out_of_range",
                    "s1_duration_ms": float(s1_dur),
                    "s2_duration_ms": float(s2_dur),
                    "systolic_ms": float(systolic),
                    "diastolic_ms": float(diastolic),
                    "cycle_duration_ms": float(cycle_dur),
                    "heart_rate_bpm": float(hr),
                })
                i += 1
                continue

            mfcc_means = safe_mfcc_means(full, sr, n_mfcc=8)

            cycle = {
                "s1_duration_ms": float(s1_dur),
                "s2_duration_ms": float(s2_dur),
                "systolic_ms": float(systolic),
                "diastolic_ms": float(diastolic),
                "cycle_duration_ms": float(cycle_dur),
                "heart_rate_bpm": float(hr),
                "sd_ratio": float(systolic / (diastolic + 1e-10)),
                "s1_rms": float(s1_rms),
                "s2_rms": float(s2_rms),
                "s1_s2_amp_ratio": float(s1_rms / (s2_rms + 1e-10)),
                "energy_concentration": float(
                    (np.sum(s1_sig ** 2) + np.sum(s2_sig ** 2)) /
                    (np.sum(full ** 2) + 1e-10)
                ),
                "s1_zcr": zero_crossing_rate(s1_sig),
                "s2_zcr": zero_crossing_rate(s2_sig),
                "s1_kurtosis": excess_kurtosis(s1_sig),
                "s2_kurtosis": excess_kurtosis(s2_sig),
                "s1_centroid": spectral_centroid(s1_sig, sr),
                "s2_centroid": spectral_centroid(s2_sig, sr),
                "sys_noise_ratio": float(sys_rms / (s1_rms + 1e-10)),
                "dia_noise_ratio": float(dia_rms / (s1_rms + 1e-10)),
                **{f"mfcc_{j}": float(v) for j, v in enumerate(mfcc_means)},
                "_s1_start": int(s1_start),
                "_s1_end": int(s1_end),
                "_sys_start": int(sys_start),
                "_sys_end": int(sys_end),
                "_s2_start": int(s2_start),
                "_s2_end": int(s2_end),
                "_dia_start": int(dia_start),
                "_dia_end": int(dia_end),
            }

            cycles.append(cycle)
            i += 4

        else:
            i += 1

    return cycles, rejected_cycles


print("✓ Feature extraction functions defined")

cycles, rejected_cycles = extract_cycle_features(
    filtered,
    segments,
    sample_rate
)
print(f"Accepted cardiac cycles: {len(cycles)}")
print(f"Rejected candidate cycles: {len(rejected_cycles)}")

# ==================================================
# EXTRACT PER-CYCLE FEATURES
# ==================================================

cycles, rejected_cycles = extract_cycle_features(
    filtered,
    segments,
    sample_rate
)

print("Cycle Feature Extraction")
print("=" * 60)
print(f"Accepted cardiac cycles:  {len(cycles)}")
print(f"Rejected candidate cycles: {len(rejected_cycles)}")

if len(cycles) == 0:
    print("No valid complete S1-Systole-S2-Diastole cycles were accepted.")
else:
    print(f"First cycle keys: {list(cycles[0].keys())[:10]} ...")

if len(rejected_cycles) > 0:
    print()
    print("Rejected cycle examples:")
    for item in rejected_cycles[:5]:
        reason = item.get("reason", "unknown")
        print(f"  Candidate {item.get('index', '?')}: {reason}")

        if reason == "duration_out_of_range":
            print(
                f"    S1={item['s1_duration_ms']:.1f} ms, "
                f"S2={item['s2_duration_ms']:.1f} ms, "
                f"Sys={item['systolic_ms']:.1f} ms, "
                f"Dia={item['diastolic_ms']:.1f} ms, "
                f"Cycle={item['cycle_duration_ms']:.1f} ms, "
                f"HR={item['heart_rate_bpm']:.1f} bpm"
            )

# ==================================================
# RULE-BASED SCREENING
# ==================================================

flagged = []

for ci, cycle in enumerate(cycles):
    violations = []

    for key, (lo, hi) in NORMAL_RANGES.items():
        if key in cycle:
            value = cycle[key]

            if value < lo:
                violations.append(f"{key}={value:.1f} < {lo}")
            elif value > hi:
                violations.append(f"{key}={value:.1f} > {hi}")

    if violations:
        flagged.append({
            "cycle_index": ci,
            "violations": violations
        })

normal_count = len(cycles) - len(flagged)
flagged_count = len(flagged)

print("Rule-Based Screening")
print("=" * 60)
print(f"Normal cycles:  {normal_count} / {len(cycles)}")
print(f"Flagged cycles: {flagged_count} / {len(cycles)}")

if flagged:
    print("\nFlagged details:")
    for item in flagged[:10]:
        print(
            f"Cycle {item['cycle_index']}: "
            f"{'; '.join(item['violations'])}"
        )

    if len(flagged) > 10:
        print(f"... and {len(flagged) - 10} more flagged cycles")
else:
    print("\nNo rule-based violations detected.")

# ==================================================
# CYCLE FEATURE SUMMARY
# ==================================================

summary_keys = [
    "heart_rate_bpm",
    "s1_duration_ms",
    "s2_duration_ms",
    "systolic_ms",
    "diastolic_ms",
    "s1_s2_amp_ratio",
    "sd_ratio",
]

print("Cycle Feature Summary")
print("=" * 70)

for key in summary_keys:
    values = np.array([c[key] for c in cycles if key in c], dtype=float)

    if len(values) > 0:
        print(
            f"{key:<18} | "
            f"mean={np.mean(values):7.2f} | "
            f"std={np.std(values):7.2f} | "
            f"min={np.min(values):7.2f} | "
            f"max={np.max(values):7.2f}"
        )

# # ── Anomaly detection (Isolation Forest) ──
# feat_keys = [k for k in cycles[0] if not k.startswith('_')]
# X = np.array([[c[k] for k in feat_keys] for c in cycles])
# X = np.nan_to_num(X)

# scaler = StandardScaler()
# X_scaled = scaler.fit_transform(X)

# iso_forest = IsolationForest(contamination=0.15, random_state=42, n_estimators=200)
# labels = iso_forest.fit_predict(X_scaled)
# scores = iso_forest.decision_function(X_scaled)

# print("Anomaly Detection (Isolation Forest)")
# print("=" * 50)
# print(f"  Normal cycles:  {np.sum(labels == 1)} / {len(cycles)}")
# print(f"  Anomaly cycles: {np.sum(labels == -1)} / {len(cycles)}")
# print(f"  Score range:    [{scores.min():.3f}, {scores.max():.3f}]")

# ==================================================
# ROBUST RULE-BASED OUTLIER SCORING
# ==================================================

outlier_keys = [
    "heart_rate_bpm",
    "s1_duration_ms",
    "s2_duration_ms",
    "systolic_ms",
    "diastolic_ms",
    "s1_s2_amp_ratio",
]

robust_outliers = []

for key in outlier_keys:
    values = np.array([c[key] for c in cycles if key in c], dtype=float)

    if len(values) < 5:
        continue

    median = np.median(values)
    mad = np.median(np.abs(values - median)) + 1e-10
    robust_z = 0.6745 * (values - median) / mad

    for idx, z in enumerate(robust_z):
        if abs(z) > 3.5:
            robust_outliers.append({
                "cycle_index": idx,
                "feature": key,
                "value": values[idx],
                "robust_z": z
            })

print("Robust Rule-Based Outlier Scoring")
print("=" * 60)
print(f"Outlier findings: {len(robust_outliers)}")

if robust_outliers:
    for item in robust_outliers[:10]:
        print(
            f"Cycle {item['cycle_index']}: "
            f"{item['feature']}={item['value']:.2f}, "
            f"robust_z={item['robust_z']:.2f}"
        )

    if len(robust_outliers) > 10:
        print(f"... and {len(robust_outliers) - 10} more findings")
else:
    print("No strong robust outliers detected.")

# ==================================================
# OUTLIER SUMMARY BY CYCLE
# ==================================================

outliers_by_cycle = {}

for item in robust_outliers:
    idx = item["cycle_index"]
    outliers_by_cycle.setdefault(idx, []).append(item)

print("Outlier Summary by Cycle")
print("=" * 60)

for idx, items in sorted(outliers_by_cycle.items(), key=lambda x: len(x[1]), reverse=True):
    print(f"Cycle {idx}: {len(items)} outlier feature(s)")
    for item in items:
        print(
            f"  - {item['feature']}: "
            f"value={item['value']:.2f}, "
            f"robust_z={item['robust_z']:.2f}"
        )

# ==================================================
# PLOT OUTLIER CYCLES
# ==================================================

cycles_to_plot = list(outliers_by_cycle.keys())

if len(cycles_to_plot) == 0:
    print("No outlier cycles to plot.")
else:
    for ci in cycles_to_plot:
        c = cycles[ci]

        start = int(c["_s1_start"])
        end = int(c["_dia_end"])

        pad = int(0.15 * sample_rate)
        start_plot = max(0, start - pad)
        end_plot = min(len(filtered_norm), end + pad)

        t = time_axis[start_plot:end_plot]

        plt.figure(figsize=(14, 4))

        plt.plot(
            t,
            filtered_norm[start_plot:end_plot],
            color="black",
            lw=0.8,
            label="Filtered signal"
        )

        plt.axvspan(
            c["_s1_start"] / sample_rate,
            c["_s1_end"] / sample_rate,
            color="#e74c3c",
            alpha=0.35,
            label="S1"
        )

        plt.axvspan(
            c["_sys_start"] / sample_rate,
            c["_sys_end"] / sample_rate,
            color="#f39c12",
            alpha=0.35,
            label="Systole"
        )

        plt.axvspan(
            c["_s2_start"] / sample_rate,
            c["_s2_end"] / sample_rate,
            color="#3498db",
            alpha=0.35,
            label="S2"
        )

        plt.axvspan(
            c["_dia_start"] / sample_rate,
            c["_dia_end"] / sample_rate,
            color="#2ecc71",
            alpha=0.35,
            label="Diastole"
        )

        outlier_text = "; ".join(
            [
                f"{item['feature']}={item['value']:.2f}"
                for item in outliers_by_cycle[ci]
            ]
        )

        plt.title(
            f"Outlier Cycle {ci}: {outlier_text}",
            fontweight="bold"
        )

        plt.xlabel("Time [s]")
        plt.ylabel("Normalized amplitude")
        plt.legend(loc="upper right")
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.show()

# ==================================================
# PER-CYCLE STATISTICS AND SHORT-WINDOW HRV METRICS
# ==================================================

stat_keys = [
    "heart_rate_bpm",
    "s1_duration_ms",
    "s2_duration_ms",
    "systolic_ms",
    "diastolic_ms",
    "s1_s2_amp_ratio",
    "sd_ratio",
]

print("Per-Cycle Statistics")
print("=" * 70)

for key in stat_keys:
    vals = np.array([c[key] for c in cycles if key in c], dtype=float)

    if len(vals) == 0:
        print(f"{key:<25}: no values")
        continue

    print(
        f"{key:<25}: "
        f"{np.mean(vals):8.1f} ± {np.std(vals):6.1f} "
        f"[{np.min(vals):7.1f} - {np.max(vals):7.1f}]"
    )


# --------------------------------------------------
# Short-window HRV-like metrics
# --------------------------------------------------

rr = np.array([c["cycle_duration_ms"] for c in cycles], dtype=float)

valid_rr = rr[(rr > 300) & (rr < 1500)]

print()
print("Short-Window HRV-like Metrics")
print("=" * 70)

if len(valid_rr) > 2:
    sdnn = np.std(valid_rr)
    rmssd = np.sqrt(np.mean(np.diff(valid_rr) ** 2))
    nn50 = np.sum(np.abs(np.diff(valid_rr)) > 50)
    pnn50 = 100 * nn50 / len(valid_rr)
    hr_vals = 60000.0 / valid_rr

    print(f"Valid RR intervals: {len(valid_rr)} / {len(rr)}")
    print(f"Heart rate:         {np.mean(hr_vals):.1f} ± {np.std(hr_vals):.1f} BPM")
    print(f"SDNN:               {sdnn:.1f} ms")
    print(f"RMSSD:              {rmssd:.1f} ms")
    print(f"pNN50:              {pnn50:.1f} %")
    print()
    print("Note: These are short-window HRV-like metrics, not clinical HRV estimates.")
else:
    print("Not enough valid RR intervals for HRV-like metrics.")

# # Classification plot
# fig, ax = plt.subplots(figsize=(18, 4))
# ax.plot(time_axis, filtered, color='gray', lw=0.3, alpha=0.4)
# for c, lab in zip(cycles, labels):
#     color = '#2ecc71' if lab == 1 else '#e74c3c'
#     alpha = 0.15 if lab == 1 else 0.45
#     ax.axvspan(c['_s1_start']/sample_rate, c['_dia_end']/sample_rate,
#                alpha=alpha, color=color)

# np_ = mpatches.Patch(color='#2ecc71', alpha=0.4, label='Normal')
# ap_ = mpatches.Patch(color='#e74c3c', alpha=0.5, label='Anomaly')
# ax.legend(handles=[np_, ap_], loc='upper right')
# ax.set_title('Normal vs. Anomaly Classification (Isolation Forest)', fontweight='bold')
# ax.set_xlabel('Time (seconds)')
# ax.set_ylabel('Amplitude')
# plt.tight_layout()
# plt.show()

# ==================================================
# NORMAL VS OUTLIER CYCLE VIEW (ROBUST RULE-BASED)
# ==================================================

outlier_cycle_indices = set(outliers_by_cycle.keys())

fig, ax = plt.subplots(figsize=(18, 4))

ax.plot(
    time_axis,
    filtered_norm,
    color="gray",
    lw=0.4,
    alpha=0.5
)

for ci, c in enumerate(cycles):
    is_outlier = ci in outlier_cycle_indices

    color = "#e74c3c" if is_outlier else "#2ecc71"
    alpha = 0.40 if is_outlier else 0.15

    ax.axvspan(
        c["_s1_start"] / sample_rate,
        c["_dia_end"] / sample_rate,
        alpha=alpha,
        color=color
    )

normal_patch = mpatches.Patch(color="#2ecc71", alpha=0.4, label="Normal cycle")
outlier_patch = mpatches.Patch(color="#e74c3c", alpha=0.5, label="Outlier cycle")

ax.legend(handles=[normal_patch, outlier_patch], loc="upper right")

ax.set_title(
    "Normal vs. Outlier Cycles (Robust Feature Outlier Check)",
    fontweight="bold"
)

ax.set_xlabel("Time (seconds)")
ax.set_ylabel("Normalized amplitude")
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# ==================================================
# FEATURE DISTRIBUTIONS
# ==================================================

fig, axes = plt.subplots(2, 3, figsize=(16, 9))

feat_plots = [
    ("heart_rate_bpm", "Heart Rate (BPM)"),
    ("s1_duration_ms", "S1 Duration (ms)"),
    ("s2_duration_ms", "S2 Duration (ms)"),
    ("systolic_ms", "Systolic Interval (ms)"),
    ("diastolic_ms", "Diastolic Interval (ms)"),
    ("s1_s2_amp_ratio", "S1/S2 Amplitude Ratio"),
]

for ax, (key, title) in zip(axes.flat, feat_plots):
    vals = np.array([c[key] for c in cycles if key in c], dtype=float)

    if len(vals) == 0:
        ax.set_title(title, fontweight="bold")
        ax.text(0.5, 0.5, "No data", ha="center", va="center", transform=ax.transAxes)
        continue

    bins = min(10, max(5, len(vals) // 2))

    ax.hist(
        vals,
        bins=bins,
        color="#3498db",
        alpha=0.7,
        edgecolor="white"
    )

    ax.axvline(
        np.mean(vals),
        color="red",
        ls="--",
        lw=1.5,
        label=f"Mean = {np.mean(vals):.1f}"
    )

    ax.axvline(
        np.median(vals),
        color="orange",
        ls=":",
        lw=1.5,
        label=f"Median = {np.median(vals):.1f}"
    )

    if key in NORMAL_RANGES:
        lo, hi = NORMAL_RANGES[key]
        ax.axvspan(
            lo,
            hi,
            alpha=0.12,
            color="green",
            label="Normal range"
        )

    ax.set_title(title, fontweight="bold")
    ax.set_xlabel(key)
    ax.set_ylabel("Count")
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=8)

plt.suptitle("Per-Cycle Feature Distributions", fontweight="bold", fontsize=14)
plt.tight_layout()
plt.show()

"""---
## Module 3: Murmur Detection & Grading

Analyzes energy during systolic and diastolic intervals.  
Normal hearts have near-silence between S1 and S2. Murmurs appear as sustained sound.

**Detectable at 250 Hz Nyquist:**
- Aortic stenosis (80–200 Hz, diamond-shaped systolic murmur)
- Mitral regurgitation components (100–200 Hz)
- Timing classification (systolic vs diastolic)

**Grading (Levine scale adaptation):**

| Grade | Description | Noise Ratio |
|-------|-------------|-------------|
| 0 | None | < 0.15 |
| 1 | Barely detectable | 0.15–0.30 |
| 2 | Faint but clear | 0.30–0.50 |
| 3 | Moderately loud | 0.50–0.70 |
| 4 | Loud | 0.70–0.90 |
| 5–6 | Very loud | > 0.90 |
"""

# ==================================================
# MURMUR-LIKE ACTIVITY DETECTION FUNCTIONS
# ==================================================

def murmur_grade(ratio):
    ratio = float(ratio)

    for i, th in enumerate(MURMUR_GRADE_THRESHOLDS):
        if ratio < th:
            return i

    return 6


def detect_murmur(filtered, cycle, sr):
    sys_sig = filtered[int(cycle["_sys_start"]):int(cycle["_sys_end"])]
    dia_sig = filtered[int(cycle["_dia_start"]):int(cycle["_dia_end"])]
    s1_rms = float(cycle["s1_rms"])

    result = {
        "systolic_murmur": False,
        "diastolic_murmur": False,
        "systolic_grade": 0,
        "diastolic_grade": 0,
        "systolic_ratio": 0.0,
        "diastolic_ratio": 0.0,
        "sys_diamond": False,
        "dia_decrescendo": False,
    }

    if s1_rms < 1e-8:
        return result

    if len(sys_sig) > 4:
        sys_rms = np.sqrt(np.mean(sys_sig ** 2))
        r = float(sys_rms / (s1_rms + 1e-10))

        result["systolic_ratio"] = r
        result["systolic_grade"] = murmur_grade(r)
        result["systolic_murmur"] = bool(r > MURMUR_GRADE_THRESHOLDS[0])

        if len(sys_sig) > 15:
            env = uniform_filter1d(
                np.abs(hilbert(sys_sig)),
                max(3, len(sys_sig) // 5)
            )

            pk_pos = np.argmax(env) / len(env)
            result["sys_diamond"] = bool(0.25 < pk_pos < 0.75)

    if len(dia_sig) > 4:
        dia_rms = np.sqrt(np.mean(dia_sig ** 2))
        r = float(dia_rms / (s1_rms + 1e-10))

        result["diastolic_ratio"] = r
        result["diastolic_grade"] = murmur_grade(r)
        result["diastolic_murmur"] = bool(r > MURMUR_GRADE_THRESHOLDS[0])

        if len(dia_sig) > 15:
            env = uniform_filter1d(
                np.abs(hilbert(dia_sig)),
                max(3, len(dia_sig) // 5)
            )

            q1 = np.mean(env[:len(env) // 4])
            q4 = np.mean(env[3 * len(env) // 4:])

            result["dia_decrescendo"] = bool(q1 > 1.5 * q4) if q4 > 0 else False

    return result


print("✓ Murmur-like activity detection functions defined")

# ==================================================
# RUN MURMUR-LIKE ACTIVITY ANALYSIS
# ==================================================

murmur_results = [
    detect_murmur(filtered, c, sample_rate)
    for c in cycles
]

sys_m = sum(1 for r in murmur_results if r["systolic_murmur"])
dia_m = sum(1 for r in murmur_results if r["diastolic_murmur"])
total = len(murmur_results)

print("Murmur-Like Activity Analysis")
print("=" * 60)
print(f"Analysis range: 0–{nyq:.0f} Hz, limited by {sample_rate} Hz sample rate")
print(f"Analyzed cycles: {total}")

if total == 0:
    print("No complete cycles available for murmur-like activity analysis.")
else:
    sys_pct = 100 * sys_m / total
    dia_pct = 100 * dia_m / total

    print()
    print(f"Systolic murmur-like activity:  {sys_m}/{total} cycles ({sys_pct:.0f}%)")

    if sys_m > 0:
        sr_v = [
            r["systolic_ratio"]
            for r in murmur_results
            if r["systolic_murmur"]
        ]

        sg_v = [
            r["systolic_grade"]
            for r in murmur_results
            if r["systolic_murmur"]
        ]

        print(f"  Avg systolic ratio: {np.mean(sr_v):.3f}")
        print(f"  Avg systolic grade: {np.mean(sg_v):.1f}/6")

        diamonds = sum(
            1
            for r in murmur_results
            if r.get("sys_diamond", False)
        )

        if diamonds:
            print(f"  Diamond-shaped pattern: {diamonds} cycles")

    print()
    print(f"Diastolic murmur-like activity: {dia_m}/{total} cycles ({dia_pct:.0f}%)")

    if dia_m > 0:
        dr_v = [
            r["diastolic_ratio"]
            for r in murmur_results
            if r["diastolic_murmur"]
        ]

        dg_v = [
            r["diastolic_grade"]
            for r in murmur_results
            if r["diastolic_murmur"]
        ]

        print(f"  Avg diastolic ratio: {np.mean(dr_v):.3f}")
        print(f"  Avg diastolic grade: {np.mean(dg_v):.1f}/6")

        decrescendos = sum(
            1
            for r in murmur_results
            if r.get("dia_decrescendo", False)
        )

        if decrescendos:
            print(f"  Decrescendo-like pattern: {decrescendos} cycles")

    print()
    print("-" * 60)

    if sys_pct > 50 or dia_pct > 50:
        print(
            f"Assessment: Significant murmur-like activity "
            f"(Sys: {sys_pct:.0f}%, Dia: {dia_pct:.0f}%)"
        )
    elif sys_pct > 20 or dia_pct > 20:
        print(
            "Assessment: Some murmur-like activity detected; "
            "this may reflect recording noise or segmentation uncertainty."
        )
    else:
        print("Assessment: No significant murmur-like activity detected.")

print()
print("Note: This is a signal analysis tool, not a medical diagnostic device.")

# ==================================================
# MURMUR-LIKE ACTIVITY VISUALIZATION
# ==================================================

fig, ax = plt.subplots(figsize=(18, 4))

ax.plot(
    time_axis,
    filtered_norm,
    color="gray",
    lw=0.4,
    alpha=0.5,
    label="Filtered signal"
)

for c, mr in zip(cycles, murmur_results):
    if mr["systolic_murmur"]:
        ax.axvspan(
            c["_sys_start"] / sample_rate,
            c["_sys_end"] / sample_rate,
            alpha=0.45,
            color="#e74c3c"
        )

    if mr["diastolic_murmur"]:
        ax.axvspan(
            c["_dia_start"] / sample_rate,
            c["_dia_end"] / sample_rate,
            alpha=0.45,
            color="#9b59b6"
        )

legend_handles = [
    mpatches.Patch(
        color="#e74c3c",
        alpha=0.5,
        label=f"Systolic murmur-like activity ({sys_m} cycles)"
    ),
    mpatches.Patch(
        color="#9b59b6",
        alpha=0.5,
        label=f"Diastolic murmur-like activity ({dia_m} cycles)"
    ),
]

ax.legend(handles=legend_handles, loc="upper right")

ax.set_title(
    "Heuristic Murmur-Like Activity Visualization",
    fontweight="bold"
)

ax.set_xlabel("Time (seconds)")
ax.set_ylabel("Normalized amplitude")
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# ==================================================
# PER-CYCLE MURMUR-LIKE RATIO VISUALIZATION
# ==================================================

detection_threshold = globals().get(
    "MURMUR_DETECTION_RATIO",
    MURMUR_GRADE_THRESHOLDS[0]
)

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

sys_ratios = np.array(
    [r["systolic_ratio"] for r in murmur_results],
    dtype=float
)

dia_ratios = np.array(
    [r["diastolic_ratio"] for r in murmur_results],
    dtype=float
)

cycle_idx = np.arange(len(murmur_results))

sys_colors = [
    "#e74c3c" if r > detection_threshold else "#3498db"
    for r in sys_ratios
]

dia_colors = [
    "#9b59b6" if r > detection_threshold else "#3498db"
    for r in dia_ratios
]

axes[0].bar(
    cycle_idx,
    sys_ratios,
    color=sys_colors,
    alpha=0.75
)

axes[0].axhline(
    y=detection_threshold,
    color="red",
    ls="--",
    lw=1.5,
    label=f"Detection threshold = {detection_threshold:.2f}"
)

axes[0].set_title("Systolic Energy Ratio per Cycle", fontweight="bold")
axes[0].set_xlabel("Cycle #")
axes[0].set_ylabel("Ratio vs S1 RMS")
axes[0].legend()
axes[0].grid(True, alpha=0.3)


axes[1].bar(
    cycle_idx,
    dia_ratios,
    color=dia_colors,
    alpha=0.75
)

axes[1].axhline(
    y=detection_threshold,
    color="red",
    ls="--",
    lw=1.5,
    label=f"Detection threshold = {detection_threshold:.2f}"
)

axes[1].set_title("Diastolic Energy Ratio per Cycle", fontweight="bold")
axes[1].set_xlabel("Cycle #")
axes[1].set_ylabel("Ratio vs S1 RMS")
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.suptitle(
    "Per-Cycle Murmur-Like Energy Ratios",
    fontweight="bold"
)

plt.tight_layout()
plt.show()